import { describe, it, expect } from "vitest";
import { historyToTurns } from "./ChatPane";
import type { HistoryMessage } from "../lib/types";

/** Terse HistoryMessage builder — only `role` is required. */
function msg(o: Partial<HistoryMessage> & Pick<HistoryMessage, "role">): HistoryMessage {
  return { content: "", timestamp: "2026-01-01T00:00:00Z", ...o };
}

const toolCall = (toolName: string, output = "") => ({
  toolName,
  output,
  isError: false,
});

// ── A real `/compact` group, as Claude Code writes it (issue #630) ───────────
//
// The CLI appends the compaction records at file positions PRECEDING the command
// that produced them, while stamping them with the time compaction FINISHED:
//
//   idx-3  system/compact_boundary            T_end     (type "system" — dropped
//                                                        by core's JSONL parser)
//   idx-2  user, isCompactSummary             T_end-1ms
//   idx-1  user, <local-command-caveat>       T_start   (`isMeta:true` — dropped
//                                                        by core's JSONL parser)
//   idx    user, <command-name>/compact…      T_start
//   idx+1  user, <local-command-stdout>       T_end+~0.2s
//
// So the two records the web actually receives for the group are the summary and
// the command echo — in that (backwards) order, 83s apart in the sample this is
// modelled on.
const T_START = "2026-07-11T21:29:47.574Z";
const T_END = "2026-07-11T21:31:10.255Z";
const T_STDOUT = "2026-07-11T21:31:10.568Z";

const CONTINUATION =
  "This session is being continued from a previous conversation that ran out of " +
  "context. The summary below covers the earlier portion of the conversation.\n\n" +
  "Summary:\n1. Primary Request and Intent:\n   The user asked for a thing.";
const CAVEAT =
  "<local-command-caveat>Caveat: The messages below were generated by the user " +
  "while running local commands. DO NOT respond to these messages or otherwise " +
  "consider them in your response unless the user explicitly asks you to." +
  "</local-command-caveat>";
const echoFor = (name: string) =>
  `<command-name>${name}</command-name>\n            <command-message>${name.slice(1)}</command-message>\n            <command-args></command-args>`;
const COMMAND_ECHO = echoFor("/compact");

/** The records of one completed `/compact`, in the order the file has them. */
function compactionGroup(): HistoryMessage[] {
  return [
    msg({ role: "assistant", uuid: "a-1", content: "…the reply before compaction" }),
    msg({ role: "user", uuid: "u-summary", timestamp: T_END, content: CONTINUATION }),
    msg({ role: "user", uuid: "u-cmd", timestamp: T_START, content: COMMAND_ECHO }),
    msg({
      role: "user",
      uuid: "u-stdout",
      timestamp: T_STDOUT,
      content: "<local-command-stdout>Compacted </local-command-stdout>",
    }),
  ];
}

describe("historyToTurns (issue #135: stable per-message id)", () => {
  it("keys each turn id on the source message's uuid", () => {
    const turns = historyToTurns([
      msg({ role: "user", content: "hi", uuid: "u-1" }),
      msg({ role: "assistant", content: "yo", uuid: "u-2" }),
    ]);
    expect(turns.map((t) => t.id)).toEqual(["u-1", "u-2"]);
    expect(turns.map((t) => t.kind)).toEqual(["user", "assistant"]);
  });

  it("disambiguates sibling messages that share one uuid with a #n suffix", () => {
    // e.g. an assistant entry with two tool_uses parses into two tool messages
    // that share the entry's uuid — the id must still be unique per turn.
    const turns = historyToTurns([
      msg({ role: "tool", uuid: "u-x", toolCall: toolCall("Bash", "a") }),
      msg({ role: "tool", uuid: "u-x", toolCall: toolCall("Read", "b") }),
      msg({ role: "tool", uuid: "u-x", toolCall: toolCall("Grep", "c") }),
    ]);
    expect(turns.map((t) => t.id)).toEqual(["u-x", "u-x#1", "u-x#2"]);
    expect(new Set(turns.map((t) => t.id)).size).toBe(3); // all unique
  });

  it("is reload-stable: the same transcript yields identical ids", () => {
    const input = [
      msg({ role: "user", uuid: "a" }),
      msg({ role: "tool", uuid: "b", toolCall: toolCall("X") }),
      msg({ role: "tool", uuid: "b", toolCall: toolCall("Y") }),
      msg({ role: "assistant", uuid: "c" }),
    ];
    expect(historyToTurns(input).map((t) => t.id)).toEqual(
      historyToTurns(input).map((t) => t.id),
    );
  });

  it("falls back to a unique generated id when a message has no uuid", () => {
    const turns = historyToTurns([msg({ role: "user" }), msg({ role: "assistant" })]);
    expect(turns[0].id).toBeTruthy();
    expect(turns[1].id).toBeTruthy();
    expect(turns[0].id).not.toBe(turns[1].id);
  });

  it("renders a `<task-notification>` user message as a subtle notification turn (issue #181)", () => {
    const notification = [
      "<task-notification>",
      "<task-id>a28e47ea552aa4a31</task-id>",
      "<status>killed</status>",
      '<summary>Agent "Map current unread + persistence" was stopped by user</summary>',
      "<note>A task-notification fires each time this agent stops…</note>",
      "</task-notification>",
    ].join("\n");
    const turns = historyToTurns([msg({ role: "user", uuid: "n-1", content: notification })]);
    expect(turns[0].kind).toBe("notification");
    expect(turns[0].id).toBe("n-1");
    // The raw XML is replaced by the human-readable summary.
    expect(turns[0]).toMatchObject({
      summary: 'Agent "Map current unread + persistence" was stopped by user',
    });
  });

  it("leaves a genuine user message that merely mentions the tag as a user bubble", () => {
    const turns = historyToTurns([
      msg({ role: "user", uuid: "u-9", content: "why does <task-notification> show up?" }),
    ]);
    expect(turns[0].kind).toBe("user");
  });

  it("threads a machine-injected turn's sender onto its user turn (#290)", () => {
    const sender = { kind: "chat" as const, project: "paddock", sessionId: "sess-b", name: "Report-back" };
    const turns = historyToTurns([
      msg({ role: "user", uuid: "h-1", content: "i typed this" }),
      msg({ role: "user", uuid: "m-1", content: "please report back", sender }),
    ]);
    // Human turn: no sender. Injected turn: carries its attribution.
    expect(turns[0].kind).toBe("user");
    expect((turns[0] as { sender?: unknown }).sender).toBeUndefined();
    expect(turns[1]).toMatchObject({ kind: "user", sender });
  });

  it("rebuilds a send_file tool call as a `file` turn, keyed on its uuid", () => {
    const envelope = JSON.stringify({
      paddockSendFile: 1,
      filename: "a.txt",
      kind: "text",
      source: "inline",
      content: "hello",
    });
    const turns = historyToTurns([
      msg({
        role: "tool",
        uuid: "f-1",
        toolCall: toolCall("mcp__paddock__send_file", envelope),
      }),
    ]);
    expect(turns[0].kind).toBe("file");
    expect(turns[0].id).toBe("f-1");
  });

  it("drops a background-consumed task-notification, keeps an un-consumed one (issue #230)", () => {
    const notif = (inner: string) =>
      `<task-notification>\n${inner}\n</task-notification>`;
    const turns = historyToTurns([
      msg({ role: "tool", uuid: "b-1", toolCall: toolCall("Bash", "Command running in background with ID: bxyz") }),
      // folded into the Bash block above → filtered out
      msg({
        role: "user",
        uuid: "n-1",
        bgConsumed: true,
        content: notif("<task-id>bxyz</task-id>\n<status>completed</status>\n<summary>done</summary>"),
      }),
      // an unrelated notification with no launch → still a subtle pill
      msg({
        role: "user",
        uuid: "n-2",
        content: notif("<task-id>orphan</task-id>\n<status>completed</status>\n<summary>Agent finished</summary>"),
      }),
    ]);
    expect(turns.map((t) => t.kind)).toEqual(["tool", "notification"]);
    expect(turns.map((t) => t.id)).toEqual(["b-1", "n-2"]);
  });

  it("renders a compaction boundary AFTER the `/compact` that produced it (#630)", () => {
    const turns = historyToTurns(compactionGroup());
    expect(turns.map((t) => t.kind)).toEqual([
      "assistant",
      "command",
      "compact",
      "commandOutput",
    ]);
    // The chip's own timestamp is the compaction's END — later than the command
    // it now follows, so visual order and wall-clock order finally agree.
    expect(turns[1]).toMatchObject({ kind: "command", command: "/compact" });
    expect(turns[2]).toMatchObject({ kind: "compact", id: "u-summary" });
  });

  it("steps over the dropped `<local-command-caveat>` between the two (#630)", () => {
    // The caveat sits between the summary and the command in the file. Core's
    // parser drops it (`isMeta:true`), but a transcript/core that lets it through
    // must not defeat the pairing — it renders as nothing either way.
    const msgs = compactionGroup();
    msgs.splice(2, 0, msg({ role: "user", uuid: "u-caveat", timestamp: T_START, content: CAVEAT }));
    const turns = historyToTurns(msgs);
    expect(turns.map((t) => t.kind)).toEqual([
      "assistant",
      "commandOutput", // the caveat, rendered as nothing
      "command",
      "compact",
      "commandOutput",
    ]);
  });

  it("leaves a compaction boundary with no `/compact` echo where it is (#630)", () => {
    // An auto-compaction (context exhausted, nobody typed `/compact`) writes the
    // continuation summary with no command echo after it. Nothing to pair with —
    // the chip stays in file order rather than being dropped or crashing.
    const turns = historyToTurns([
      msg({ role: "assistant", uuid: "a-1", content: "…earlier reply" }),
      msg({ role: "user", uuid: "u-summary", timestamp: T_END, content: CONTINUATION }),
      msg({ role: "assistant", uuid: "a-2", content: "carrying on" }),
    ]);
    expect(turns.map((t) => t.kind)).toEqual(["assistant", "compact", "assistant"]);
    expect(turns.map((t) => t.id)).toEqual(["a-1", "u-summary", "a-2"]);
  });

  it("leaves a `/compact` whose compaction never completed alone (#630)", () => {
    // Killed/failed compaction: the command echo is there, the summary never
    // arrives. The command chip must still render exactly once, in place.
    const turns = historyToTurns([
      msg({ role: "user", uuid: "u-cmd", timestamp: T_START, content: COMMAND_ECHO }),
      msg({ role: "assistant", uuid: "a-2", content: "…" }),
    ]);
    expect(turns.map((t) => t.kind)).toEqual(["command", "assistant"]);
  });

  it("does not re-order a compaction boundary past an unrelated slash command (#630)", () => {
    const turns = historyToTurns([
      msg({ role: "user", uuid: "u-summary", timestamp: T_END, content: CONTINUATION }),
      msg({ role: "user", uuid: "u-cmd", timestamp: T_START, content: echoFor("/context") }),
    ]);
    expect(turns.map((t) => t.kind)).toEqual(["compact", "command"]);
  });

  it("renders a server-appended usage-limit notice as a notice turn, not a bubble (#329)", () => {
    const notice = {
      kind: "usage_limit" as const,
      message: "You've hit your session limit · resets 7:10pm (America/New_York)",
      resetTime: "7:10pm (America/New_York)",
      retryable: false,
    };
    const turns = historyToTurns([
      msg({ role: "user", content: "hi?", uuid: "u-1" }),
      // The synthetic shell the server appends: role assistant, empty content, but
      // a `notice` — it must never render as an (empty) assistant bubble.
      msg({ role: "assistant", content: "", uuid: "notice-sess", notice }),
    ]);
    expect(turns.map((t) => t.kind)).toEqual(["user", "notice"]);
    const noticeTurn = turns[1];
    expect(noticeTurn.kind === "notice" && noticeTurn.notice.resetTime).toBe(
      "7:10pm (America/New_York)",
    );
  });
});
