/**
 * fonts.mjs — font plumbing for caption rendering.
 *
 * WHAT ACTUALLY HAPPENED (read this before "fixing" anything):
 *  - The app self-hosts Inter + JetBrains Mono as *variable* woff2 (latin
 *    subset) at ../../packages/web/public/fonts/. Those files are READ ONLY
 *    here — build-fonts.mjs copies them out before touching them.
 *  - ffmpeg's drawtext (libfreetype) and librsvg both want TTF/OTF, so the
 *    woff2s were converted with fontTools (`pip install fonttools brotli`),
 *    and static instances were cut at the weights we actually use:
 *      Inter wght=400 -> Inter-Regular.ttf
 *      Inter wght=600 -> Inter-SemiBold.ttf
 *      JetBrains Mono wght=500 -> JetBrainsMono-Medium.ttf
 *    Static instances (rather than shipping the variable font) because
 *    fontconfig/pango weight selection across a variable TTF is unreliable,
 *    whereas two static faces with the right usWeightClass Just Work.
 *  - The app sets `font-feature-settings: "cv05","ss01"` on <body>, but the
 *    SHIPPED SUBSET CONTAINS NEITHER FEATURE (its GSUB is calt/ccmp/dnom/frac/
 *    locl/numr/pnum/tnum). So that CSS is a no-op in the product, and captions
 *    rendered without those features match the real UI exactly. Do not "fix"
 *    this by freezing features in — that would make captions differ from the app.
 *
 * Rendering goes through librsvg (ffmpeg's `svg` decoder), which resolves fonts
 * via fontconfig. We generate a private fonts.conf so we never depend on the
 * system font set — except as a deliberate LAST-RESORT fallback for codepoints
 * the latin subset does not cover (see FALLBACK_DIRS).
 */
import fs from "node:fs";
import path from "node:path";
import { FONT_DIR, LIB_DIR, TMP_DIR } from "./paths.mjs";

export { FONT_DIR, TMP_DIR };

/**
 * The generated fontconfig file lives in TMP_DIR, not next to the fonts:
 * `ensureFontConfig()` runs on every caption render, and nothing under `video/`
 * may write into the repo working tree at runtime. FONT_DIR only ever holds
 * build-time output.
 */
export const FONTCONFIG_FILE = path.join(TMP_DIR, "fonts.conf");
export const COVERAGE_FILE = path.join(FONT_DIR, "coverage.json");

/**
 * System font dirs are appended AFTER ours purely so that a stray codepoint
 * outside the latin subset renders as *something* (DejaVu) instead of silently
 * disappearing. Inter always wins for anything it covers because it is listed
 * first and matched by exact family name.
 */
const FALLBACK_DIRS = ["/usr/share/fonts", "/usr/local/share/fonts"].filter((d) => fs.existsSync(d));

export const FAMILY = {
  sans: "Inter",
  mono: "JetBrains Mono",
};

/** Idempotently (re)write the private fontconfig file and return its path. */
export function ensureFontConfig() {
  fs.mkdirSync(TMP_DIR, { recursive: true });
  const xml = `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- generated by fonts.mjs; edit that, not this -->
<fontconfig>
  <dir>${FONT_DIR}</dir>
${FALLBACK_DIRS.map((d) => `  <dir>${d}</dir>`).join("\n")}
  <cachedir>${path.join(TMP_DIR, "fccache")}</cachedir>
  <include ignore_missing="yes">/etc/fonts/conf.d</include>
  <match target="font">
    <edit name="antialias" mode="assign"><bool>true</bool></edit>
    <edit name="hinting" mode="assign"><bool>false</bool></edit>
    <edit name="rgba" mode="assign"><const>none</const></edit>
  </match>
</fontconfig>
`;
  const prev = fs.existsSync(FONTCONFIG_FILE) ? fs.readFileSync(FONTCONFIG_FILE, "utf8") : null;
  if (prev !== xml) fs.writeFileSync(FONTCONFIG_FILE, xml, "utf8");
  return FONTCONFIG_FILE;
}

/** env for any child process that rasterises text. */
export function fontEnv(extra = {}) {
  return { ...process.env, FONTCONFIG_FILE: ensureFontConfig(), ...extra };
}

let coverage = null;
/**
 * Codepoints Inter's latin subset actually covers, as a Set of numbers.
 * Built once by build-fonts.mjs; absent => coverage checking is skipped.
 */
export function interCoverage() {
  if (coverage !== null) return coverage;
  try {
    const j = JSON.parse(fs.readFileSync(COVERAGE_FILE, "utf8"));
    coverage = new Set(j.Inter);
  } catch {
    coverage = false;
  }
  return coverage;
}

/**
 * Characters in `text` that Inter cannot render. These do NOT vanish (we fall
 * back to system fonts) but they WILL look wrong — different face, different
 * weight — so callers should surface them loudly.
 */
export function uncoveredChars(text) {
  const cov = interCoverage();
  if (!cov) return [];
  const bad = [];
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    if (cp === 0x20 || cp === 0x0a) continue;
    if (!cov.has(cp)) bad.push(ch);
  }
  return [...new Set(bad)];
}

export function assertFontsPresent() {
  const need = ["Inter-Regular.ttf", "Inter-SemiBold.ttf", "JetBrainsMono-Medium.ttf"];
  const missing = need.filter((f) => !fs.existsSync(path.join(FONT_DIR, f)));
  if (missing.length) {
    throw new Error(
      `missing converted fonts: ${missing.join(", ")}\n` +
      `run:  env -u NODE_ENV node ${path.join(LIB_DIR, "build-fonts.mjs")}`,
    );
  }
}
